site_name: SPARQL Anything
repo_url: https://github.com/SPARQL-Anything/sparql.anything
repo_name: GitHub
edit_uri: null
site_description: SPARQL Anything online documentation
theme:
  name: readthedocs
#nav: null
extra_css: [docs/styles.css]
sticky_navigation: true
markdown_extensions:
  - tables